{{- if .Values.rbac.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ if .Values.rbac.clusterRoleBinding.fullnameOverride }}{{ .Values.rbac.clusterRoleBinding.fullnameOverride }}{{ else }}{{ include "generic-helm-charts.fullname" . }}{{ end }}
  labels:
    {{- include "generic-helm-charts.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ toYaml .Values.rbac.clusterRoleBinding.spec }}
{{- end }}