{{- $fullName := include "generic-helm-charts.fullname" . -}}
{{- range $name, $entries := (omit .Values.configmaps "nochecksum") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-{{ $name }}
data:
{{- range $path, $files := (omit $entries "nochecksum") }}
{{- range $filename, $details := (omit $files "nochecksum") }}
  {{ $filename }}: |-
    {{- $details.contents | nindent 4 }}
{{- end }}
{{- end }}
---
{{- end }}