{{- $fullName := include "generic-helm-charts.fullname" . -}}
{{- $configmapName := include "generic-helm-charts.configmapname" . -}}
{{- $labels := include "generic-helm-charts.labels" . -}}
{{- if .Values.configmaps }}
{{- range $name, $entries := (omit .Values.configmaps "nochecksum") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}-{{ $name }}
  labels:
    {{- $labels | nindent 4 }}
    {{- if $entries.labels }}
    {{- toYaml $entries.labels | nindent 4 }}
    {{- end }}
data:
{{- range $path, $files := (omit $entries "nochecksum" "labels") }}
{{- range $filename, $details := (omit $files "nochecksum") }}
  {{ $filename }}: |-
    {{- $details.contents | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.extraConfigmaps }}
{{- range $name, $entries := (omit .Values.extraConfigmaps "nochecksum") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if $entries.fullnameOverride }}{{ $entries.fullnameOverride }}{{ else }}{{ $configmapName }}-{{ $name }}{{ end }}
  labels:
    {{- $labels | nindent 4 }}
    {{- if $entries.labels }}
    {{- toYaml $entries.labels | nindent 4 }}
    {{- end }}
data:
{{- range $filename, $details := (omit $entries "nochecksum" "fullnameOverride" "labels") }}
  {{ $filename }}: |-
    {{- $details.contents | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}