{{- $fullName := include "generic-helm-chart.fullname" . -}}
{{- range $name, $entries := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-{{ $name }}
data:
{{- range $path, $files := $entries }}
{{- range $filename, $contents := $files }}
  {{ $filename }}: |-
    {{- $contents | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}