{{- $fullName := include "generic-helm-charts.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-helm-charts.fullname" . }}
  labels:
    {{- include "generic-helm-charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic-helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if (or .Values.podAnnotations .Values.configmaps) }}
      {{- if (not .Values.configmaps.nochecksum) }}
      annotations:
      {{- with (omit .Values.configmaps "nochecksum") }}
        configchecksum:
          {{- range $name, $entries := . }}
          {{- if not $entries.nochecksum }}
          {{- range $path, $files := (omit $entries "nochecksum") }}
          {{- if not $files.nochecksum }}
          {{- range $filename, $details := (omit $files "nochecksum") }}
          {{- if not $details.nochecksum }}
          {{ $name }}:{{ $path }}/{{ $filename }}={{ $details.contents | sha256sum | trunc 63 }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "generic-helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic-helm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          {{- range $name, $value := .Values.env.open }}
          {{- if not (empty $value) }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- range $name, $value := .Values.env.field }}
          {{- if not ( empty $value) }}
            - name: {{ $name | quote }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.env.existingSecret }}
          {{- $secret_name := .Values.env.existingSecret }}
          {{- range $name, $key := .Values.env.existingSecretMappings }}
          {{- if not ( empty $key) }}
            - name: {{ $name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name | quote }}
                  key: {{ $key | quote }}
          {{- end }}
          {{- end }}
          {{- else }}
          {{- $secret_name := include "generic-helm-charts.fullname" . }}
          {{- range $name, $value := .Values.env.secret }}
          {{- if not ( empty $value) }}
            - name: {{ $name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name }}
                  key: {{ $name | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ default "/" .Values.livenessProbe.monitorPath }}
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ default 0 .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 10 .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ default 1 .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ default 1 .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ default 3 .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ default "/" .Values.readinessProbe.monitorPath }}
              port: http
              scheme: HTTP
            initialDelaySeconds: {{ default 0 .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ default 10 .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ default 1 .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ default 1 .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ default 3 .Values.readinessProbe.failureThreshold }}
          {{- if .Values.configmaps }}
          volumeMounts:
            {{- range $name, $entries := (omit .Values.configmaps "nochecksum") }}
            {{- range $path, $files := (omit $entries "nochecksum") }}
            {{- if (gt (len (keys (omit $entries "nochecksum"))) 1) }}
            {{- range $filename, $details := (omit $files "nochecksum") }}
            - name: {{ $name }}
              mountPath: {{ $path }}/{{ $filename }}
              subPath: {{ $path }}/{{ $filename }}
            {{- end }}
            {{- else }}
            - name: {{ $name }}
              mountPath: {{ $path }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.configmaps }}
      volumes:
        {{- range $name, $files := (omit .Values.configmaps "nochecksum") }}
        - name: {{ $name }}
          configMap:
            name: {{ $fullName }}-{{ $name }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
