{{- if .Values.rbac.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "generic-helm-charts.fullname" . }}
  labels:
    {{- include "generic-helm-charts.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ toYaml .Values.rbac.clusterRole.spec }}
{{- end }}
